chore: add auto-merge workflow and update renovate configuration for improved automerging

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -1,4 +1,4 @@
-name: test
+name: Pull Request
 
 on:
   pull_request:
@@ -8,11 +8,8 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
-    permissions:
-      pull-requests: write
     steps:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-
       - name: Set up Go
         uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
         with:
@@ -25,3 +22,21 @@ jobs:
 
       - name: Build and Test
         run: make build
+
+  status-check:
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    if: always()
+    steps:
+      - name: Check status
+        run: |
+          if [[ "${{ needs.test.result }}" == "failure" ]]; then
+            echo "Test job failed"
+            exit 1
+          elif [[ "${{ needs.test.result }}" == "cancelled" ]]; then
+            echo "Test job was cancelled"
+            exit 1
+          else
+            echo "All jobs succeeded or were skipped"
+          fi
